services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - '5415:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8085
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=hyspKwOUZirYTCPbUCgP9yR56265dvdvdv6aSn1OOhy
      - SESSION_DRIVER=cookie
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    ports:
      - '8085:8085'
    depends_on:
      - db

volumes:
  db:
    driver: local
