services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - '5415:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3333
      - HOST=127.0.0.1
      - LOG_LEVEL=info
      - APP_KEY=hyspKwOUZirYTCPbUCgP9yR56265dvdvdv6aSn1OOhy
      - SESSION_DRIVER=cookie
      - DB_CONNECTION=pg
      - PG_HOST=db
      - PG_PORT=5415
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB_NAME=postgres
    ports:
      - '3333:3333'
    depends_on:
      - db

volumes:
  db:
    driver: local
